export const GET_DETAILS_REQUEST = "GET_DETAILS_REQUEST";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAILURE = "GET_DETAILS_FAILURE";

export const ADD_DETAILS_REQUEST = "ADD_DETAILS_REQUEST";
export const ADD_DETAILS_SUCCESS = "ADD_DETAILS_SUCCESS";
export const ADD_DETAILS_FAILURE = "ADD_DETAILS_FAILURE";

export const EDIT_DETAILS_REQUEST = "EDIT_DETAILS_REQUEST";
export const EDIT_DETAILS_SUCCESS = "EDIT_DETAILS_SUCCESS";
export const EDIT_DETAILS_FAILURE = "EDIT_DETAILS_FAILURE";

export const PATCH_DETAILS_REQUEST = "PATCH_DETAILS_REQUEST";
export const PATCH_DETAILS_SUCCESS = "PATCH_DETAILS_SUCCESS";
export const PATCH_DETAILS_FAILURE = "PATCH_DETAILS_FAILURE";

export const DELETE_DETAILS_REQUEST = "DELETE_DETAILS_REQUEST";
export const DELETE_DETAILS_SUCCESS = "DELETE_DETAILS_SUCCESS";
export const DELETE_DETAILS_FAILURE = "DELETE_DETAILS_FAILURE";
